export const parameter = {
    airplanePart: {
        physicalModel: {
            Engine: [
                { engine_type: 'Engine Type', type: 'string' },
                { horsepower: 'Horsepower', type: 'int' },
                { rpm: 'RPM', type: 'int' },
                { displacement: 'Displacement', type: 'float' },
                { fuel_type_avgas: 'Fuel Type (AVGAS)', type: 'string' },
                { fuel_consumption: 'Fuel Consumption (GPH)', type: 'float' },
                { compression_ratio: 'Compression Ratio', type: 'float' },
                { torque: 'Torque (lb-ft)', type: 'int' },
                { egt: 'Exhaust Gas Temperature (EGT)', type: 'int' },
                { cht: 'Cylinder Head Temperature (CHT)', type: 'int' },
                { oil_pressure: 'Oil Pressure (PSI)', type: 'int' },
                { oil_temperature: 'Oil Temperature (°F)', type: 'int' }
            ],
            LandingGear: [
                { tire_type: 'Tire Type', type: 'string' },
                { material: 'Material', type: 'string' },
                { shock_absorption: 'Shock Absorption', type: 'string' },
                { tire_pressure: 'Tire Pressure (PSI)', type: 'int' },
                { retraction_system: 'Retraction System', type: 'string' },
                { braking_system: 'Braking System', type: 'string' },
                { track_width: 'Track Width (ft)', type: 'float' },
                { tire_size: 'Tire Size (in)', type: 'float' },
                { weight_capacity: 'Weight Capacity (lbs)', type: 'int' }
            ],
            FuelSystem: [
                { fuel_tank_capacity: 'Fuel Tank Capacity (gallons)', type: 'float' },
                { fuel_type: 'Fuel Type', type: 'string' },
                { fuel_delivery_system: 'Fuel Delivery System', type: 'string' },
                { fuel_pressure: 'Fuel Pressure (PSI)', type: 'int' },
                { fuel_pumps: 'Fuel Pumps', type: 'string' },
                { fuel_lines: 'Fuel Lines Type', type: 'string' },
                { fuel_filter: 'Fuel Filter', type: 'string' },
                { fuel_selector_valve: 'Fuel Selector Valve', type: 'string' },
                { fuel_flow_indicator: 'Fuel Flow Indicator (GPH)', type: 'float' },
                { fuel_venting: 'Fuel Venting System', type: 'string' }
            ],
            CockpitControls: [
                { control_column: 'Control Column', type: 'string' },
                { throttle: 'Throttle Control', type: 'string' },
                { mixture_control: 'Mixture Control', type: 'string' },
                { flaps_control: 'Flaps Control', type: 'string' },
                { trim_control: 'Trim Control', type: 'string' },
                { rudder_pedals: 'Rudder Pedals', type: 'string' },
                { landing_gear_control: 'Landing Gear Control', type: 'string' },
                { brakes: 'Brakes', type: 'string' },
                { avionics_master: 'Avionics Master Switch', type: 'string' },
                { autopilot: 'Autopilot Control', type: 'string' },
                { flight_instruments: 'Flight Instruments', type: 'array' },
                { communication_radio: 'Communication Radio', type: 'string' },
                { navigation_radio: 'Navigation Radio', type: 'string' },
                { transponder: 'Transponder', type: 'string' },
                { fuel_gauge: 'Fuel Gauge', type: 'string' },
                { altimeter: 'Altimeter', type: 'string' },
                { airspeed_indicator: 'Airspeed Indicator', type: 'string' },
                { attitude_indicator: 'Attitude Indicator', type: 'string' },
                { heading_indicator: 'Heading Indicator', type: 'string' },
                { vertical_speed_indicator: 'Vertical Speed Indicator', type: 'string' }
            ],
            Avionics: [
                { gps: 'GPS System', type: 'string' },
                { nav_com: 'Nav/Com Radio', type: 'string' },
                { adf: 'ADF (Automatic Direction Finder)', type: 'string' },
                { vor: 'VOR (VHF Omnidirectional Range)', type: 'string' },
                { dme: 'DME (Distance Measuring Equipment)', type: 'string' },
                { transponder: 'Transponder', type: 'string' },
                { elt: 'ELT (Emergency Locator Transmitter)', type: 'string' },
                { adsb: 'ADS-B (Automatic Dependent Surveillance-Broadcast)', type: 'string' },
                { weather_radar: 'Weather Radar', type: 'string' },
                { autopilot_system: 'Autopilot System', type: 'string' },
                { flight_director: 'Flight Director', type: 'string' },
                { tcas: 'TCAS (Traffic Collision Avoidance System)', type: 'string' },
                { glass_cockpit: 'Glass Cockpit Display', type: 'string' },
                { mfd: 'MFD (Multi-Function Display)', type: 'string' },
                { pfd: 'PFD (Primary Flight Display)', type: 'string' },
                { audio_panel: 'Audio Panel', type: 'string' },
                { transponder_modes: 'Transponder Modes', type: 'string' }
            ],
            ElectricalSystem: [
                { battery_capacity: 'Battery Capacity (Ah)', type: 'int' },
                { alternator_rating: 'Alternator Rating (Amps)', type: 'int' },
                { voltage: 'System Voltage (Volts)', type: 'int' },
                { wiring_type: 'Wiring Type', type: 'string' },
                { circuit_breakers: 'Circuit Breakers', type: 'string' },
                { electrical_buses: 'Electrical Buses', type: 'string' },
                { master_switch: 'Master Switch', type: 'string' },
                { generator: 'Generator Output (Amps)', type: 'int' },
                { inverters: 'Inverters', type: 'string' },
                { power_outlets: 'Power Outlets', type: 'string' },
                { lighting_system: 'Lighting System', type: 'string' },
                { avionics_power: 'Avionics Power Supply', type: 'string' },
                { battery_type: 'Battery Type', type: 'string' },
                { backup_battery: 'Backup Battery', type: 'string' },
                { bus_voltage_monitoring: 'Bus Voltage Monitoring', type: 'string' },
                { electrical_fault_monitoring: 'Electrical Fault Monitoring', type: 'string' }
            ],
            FlightInstruments: [
                { altimeter: 'Altimeter', type: 'string' },
                { airspeed_indicator: 'Airspeed Indicator', type: 'string' }, 
                { attitude_indicator: 'Attitude Indicator', type: 'string' }, 
                { heading_indicator: 'Heading Indicator', type: 'string' }, 
                { vertical_speed_indicator: 'Vertical Speed Indicator', type: 'string' }, 
                { turn_coordinator: 'Turn Coordinator', type: 'string' }, 
                { gyro_horizon: 'Gyro Horizon', type: 'string' }, 
                { compass: 'Compass', type: 'string' }, 
                { tachometer: 'Tachometer', type: 'string' },
                { fuel_gauge: 'Fuel Gauge', type: 'string' },
                { oil_pressure_gauge: 'Oil Pressure Gauge', type: 'string' },
                { oil_temperature_gauge: 'Oil Temperature Gauge', type: 'string' },
                { manifold_pressure_gauge: 'Manifold Pressure Gauge', type: 'string' },
                { engine_temperature_gauge: 'Engine Temperature Gauge', type: 'string' }, 
                { vacuum_gauge: 'Vacuum Gauge', type: 'string' } 
            ],            
            Brakes: [
                { brake_type: 'Brake Type', type: 'string' },
                { brake_material: 'Brake Material', type: 'string' },
                { brake_size: 'Brake Size', type: 'int' },
                { brake_pressure: 'Brake Pressure', type: 'int' },
                { brake_system: 'Brake System', type: 'string' },
                { anti_skid_system: 'Anti-Skid System', type: 'string' },
                { parking_brake: 'Parking Brake', type: 'string' },
                { brake_lines: 'Brake Lines', type: 'string' },
                { brake_pads: 'Brake Pads', type: 'string' },
                { brake_fluid: 'Brake Fluid Type', type: 'string' }
            ],
            ExhaustSystem: [
                { exhaust_type: 'Exhaust Type', type: 'string' },
                { material: 'Material', type: 'string' },
                { exhaust_pipe_diameter: 'Exhaust Pipe Diameter (in)', type: 'float' },
                { muffler_type: 'Muffler Type', type: 'string' },
                { heat_shields: 'Heat Shields', type: 'string' },
                { exhaust_gaskets: 'Exhaust Gaskets', type: 'string' },
                { exhaust_temperature: 'Exhaust Temperature (°F)', type: 'int' },
                { exhaust_system_pressure: 'Exhaust System Pressure (PSI)', type: 'int' },
                { exhaust_system_mounting: 'Exhaust System Mounting', type: 'string' },
                { emission_control: 'Emission Control', type: 'string' }
            ],
            CoolingSystem: [
                { cooling_type: 'Cooling Type', type: 'string' },
                { coolant_type: 'Coolant Type', type: 'string' },
                { radiator_size: 'Radiator Size (inches)', type: 'int' },
                { cooling_fan: 'Cooling Fan', type: 'string' },
                { oil_cooler: 'Oil Cooler', type: 'string' },
                { cooling_system_pressure: 'Cooling System Pressure (PSI)', type: 'int' },
                { thermostat: 'Thermostat', type: 'string' },
                { temperature_gauge: 'Temperature Gauge', type: 'string' },
                { cooling_system_pumps: 'Cooling System Pumps', type: 'string' },
                { coolant_capacity: 'Coolant Capacity (gallons)', type: 'float' },
                { airflow_management: 'Airflow Management', type: 'string' },
                { cooling_fins: 'Cooling Fins', type: 'string' },
                { cooling_system_mounting: 'Cooling System Mounting', type: 'string' }
            ],
            Powerplant: [
                { engine_type: 'Engine Type', type: 'string' },
                { engine_model: 'Engine Model', type: 'string' },
                { horsepower: 'Horsepower', type: 'int' },
                { rpm: 'RPM', type: 'int' },
                { displacement: 'Displacement (L)', type: 'float' },
                { fuel_type: 'Fuel Type', type: 'string' },
                { compression_ratio: 'Compression Ratio', type: 'float' },
                { turbocharger: 'Turbocharger', type: 'string' },
                { intercooler: 'Intercooler', type: 'string' },
                { fuel_injection: 'Fuel Injection', type: 'string' },
                { ignition_system: 'Ignition System', type: 'string' },
                { cooling_system: 'Cooling System', type: 'string' },
                { exhaust_system: 'Exhaust System', type: 'string' },
                { oil_system: 'Oil System', type: 'string' },
                { power_output: 'Power Output (kW)', type: 'float' },
                { operating_temperature: 'Operating Temperature (°C)', type: 'int' },
                { weight: 'Weight (lbs)', type: 'int' },
                { maintenance_intervals: 'Maintenance Intervals', type: 'string' }
            ]
            
        }
    }
}