export const parameter = {
    airplanePart: {
        physicalModel: {
            Engine: [
                { name: 'Engine Type', type: 'string' },
                { name: 'Horsepower', type: 'int' },
                { name: 'RPM', type: 'int' },
                { name: 'Displacement', type: 'float' },
                { name: 'Fuel Type (AVGAS)', type: 'string' },
                { name: 'Fuel Consumption (GPH)', type: 'float' },
                { name: 'Compression Ratio', type: 'float' },
                { name: 'Torque (lb-ft)', type: 'int' },
                { name: 'Exhaust Gas Temperature (EGT)', type: 'int' },
                { name: 'Cylinder Head Temperature (CHT)', type: 'int' },
                { name: 'Oil Pressure (PSI)', type: 'int' },
                { name: 'Oil Temperature (°F)', type: 'int' }
            ],
            LandingGear: [
                { name: 'Tire Type', type: 'string' },
                { name: 'Material', type: 'string' },
                { name: 'Shock Absorption', type: 'string' },
                { name: 'Tire Pressure (PSI)', type: 'int' },
                { name: 'Retraction System', type: 'string' },
                { name: 'Braking System', type: 'string' },
                { name: 'Track Width (ft)', type: 'float' },
                { name: 'Tire Size (in)', type: 'float' },
                { name: 'Weight Capacity (lbs)', type: 'int' }
            ],
            FuelSystem: [
                { name: 'Fuel Tank Capacity (gallons)', type: 'float' },
                { name: 'Fuel Type', type: 'string' },
                { name: 'Fuel Delivery System', type: 'string' },
                { name: 'Fuel Pressure (PSI)', type: 'int' },
                { name: 'Fuel Pumps', type: 'string' },
                { name: 'Fuel Lines Type', type: 'string' },
                { name: 'Fuel Filter', type: 'string' },
                { name: 'Fuel Selector Valve', type: 'string' },
                { name: 'Fuel Flow Indicator (GPH)', type: 'float' },
                { name: 'Fuel Venting System', type: 'string' }
            ],
            CockpitControls: [
                { name: 'Control Yoke/stick', type: 'string' },
                { name: 'Throttle', type: 'string' },
                { name: 'Rudder Pedals', type: 'string' },
                { name: 'Trim Controls', type: 'string' },
                { name: 'Flap Controls', type: 'string' },
                { name: 'Autopilot', type: 'string' },
                { name: 'Landing Gear Controls', type: 'string' },
                { name: 'Radio Panel', type: 'string' },
                { name: 'Instrument Panel', type: 'string' }
            ],
            Avionics: [
                { name: 'GPS System', type: 'string' },
                { name: 'Nav/Com Radio', type: 'string' },
                { name: 'ADF (Automatic Direction Finder)', type: 'string' },
                { name: 'VOR (VHF Omnidirectional Range)', type: 'string' },
                { name: 'DME (Distance Measuring Equipment)', type: 'string' },
                { name: 'Transponder', type: 'string' },
                { name: 'ELT (Emergency Locator Transmitter)', type: 'string' },
                { name: 'ADS-B (Automatic Dependent Surveillance-Broadcast)', type: 'string' },
                { name: 'Weather Radar', type: 'string' },
                { name: 'Autopilot System', type: 'string' },
                { name: 'Flight Director', type: 'string' },
                { name: 'TCAS (Traffic Collision Avoidance System)', type: 'string' },
                { name: 'Transponder Modes', type: 'string' }
            ],
            ElectricalSystem: [
                { name: 'Battery Capacity (Ah)', type: 'int' },
                { name: 'Alternator Rating (Amps)', type: 'int' },
                { name: 'System Voltage (Volts)', type: 'int' },
                { name: 'Wiring Type', type: 'string' },
                { name: 'Circuit Breakers', type: 'string' },
                { name: 'Electrical Buses', type: 'string' },
                { name: 'Master Switch', type: 'string' },
                { name: 'Generator Output (Amps)', type: 'int' },
                { name: 'Inverters', type: 'string' },
                { name: 'Power Outlets', type: 'string' },
                { name: 'Lighting System', type: 'string' },
                { name: 'Avionics Power Supply', type: 'string' },
                { name: 'Battery Type', type: 'string' },
                { name: 'Backup Battery', type: 'string' },
                { name: 'Electrical Fault Monitoring', type: 'string' }
            ],
            FlightInstruments: [
                { name: 'Altimeter', type: 'string' },
                { name: 'Airspeed Indicator', type: 'string' }, 
                { name: 'Heading Indicator', type: 'string' }, 
                { name: 'Vertical Speed Indicator', type: 'string' }, 
                { name: 'Turn Coordinator', type: 'string' }, 
                { name: 'Gyro Horizon', type: 'string' }, 
                { name: 'Compass', type: 'string' }, 
                { name: 'Tachometer', type: 'string' },
                { name: 'Fuel Gauge', type: 'string' },
                { name: 'Oil Pressure Gauge', type: 'string' },
                { name: 'Oil Temperature Gauge', type: 'string' },
                { name: 'Manifold Pressure Gauge', type: 'string' },
                { name: 'Engine Temperature Gauge', type: 'string' }, 
                { name: 'Vacuum Gauge', type: 'string' } 
            ],            
            Brakes: [
                { name: 'Brake Type', type: 'string' },
                { name: 'Brake Material', type: 'string' },
                { name: 'Brake Size', type: 'int' },
                { name: 'Brake Pressure', type: 'int' },
                { name: 'Brake System', type: 'string' },
                { name: 'Anti-Skid System', type: 'string' },
                { name: 'Parking Brake', type: 'string' },
                { name: 'Brake Lines', type: 'string' },
                { name: 'Brake Pads', type: 'string' },
                { name: 'Brake Fluid Type', type: 'string' }
            ],
            ExhaustSystem: [
                { name: 'Exhaust Type', type: 'string' },
                { name: 'Material', type: 'string' },
                { name: 'Exhaust Pipe Diameter (in)', type: 'float' },
                { name: 'Muffler Type', type: 'string' },
                { name: 'Heat Shields', type: 'string' },
                { name: 'Exhaust Gaskets', type: 'string' },
                { name: 'Exhaust Temperature (°F)', type: 'int' },
                { name: 'Exhaust System Pressure (PSI)', type: 'int' },
                { name: 'Exhaust System Mounting', type: 'string' },
                { name: 'Emission Control', type: 'string' }
            ],
            CoolingSystem: [
                { name: 'Coolant Type', type: 'string' },
                { name: 'Radiator Size (inches)', type: 'int' },
                { name: 'Cooling Fan', type: 'string' },
                { name: 'Oil Cooler', type: 'string' },
                { name: 'Cooling System Pressure (PSI)', type: 'int' },
                { name: 'Thermostat', type: 'string' },
                { name: 'Temperature Gauge', type: 'string' },
                { name: 'Cooling System Pumps', type: 'string' },
                { name: 'Coolant Capacity (gallons)', type: 'float' },
                { name: 'Airflow Management', type: 'string' },
                { name: 'Cooling Fins', type: 'string' },
                { name: 'Cooling System Mounting', type: 'string' }
            ],
            Powerplant: [
                { name: 'Engine Type', type: 'string' },
                { name: 'Engine Model', type: 'string' },
                { name: 'Horsepower', type: 'int' },
                { name: 'RPM', type: 'int' },
                { name: 'Displacement (L)', type: 'float' },
                { name: 'Fuel Type', type: 'string' },
                { name: 'Compression Ratio', type: 'float' },
                { name: 'Turbocharger', type: 'string' },
                { name: 'Intercooler', type: 'string' },
                { name: 'Fuel Injection', type: 'string' },
                { name: 'Ignition System', type: 'string' },
                { name: 'Cooling System', type: 'string' },
                { name: 'Exhaust System', type: 'string' },
                { name: 'Oil System', type: 'string' },
                { name: 'Power Output (kW)', type: 'float' },
                { name: 'Operating Temperature (°C)', type: 'int' },
                { name: 'Weight (lbs)', type: 'int' },
                { name: 'Maintenance Intervals', type: 'string' }
            ]
            
        }
    }
}