/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 cirrussr22.gltf 
Author: KOG_THORNS (https://sketchfab.com/ioai25312)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cirrus-sr22-cba602c99c524cd4b40e5c2e5f9c5b4f
Title: Cirrus SR22
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('./cirrussr22.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Aviyonik1Mtl} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Aviyonik2Mtl} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Aviyonik31Mtl} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Aviyonik41Mtl} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Aviyonik61Mtl} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Aviyonik71Mtl} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.Aviyonik91Mtl} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.Floor1Mtl} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.Joystick1Mtl} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.Prop1Mtl} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.Spinner1Mtl} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.Aviyonik21Mtl} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.Aviyonik81Mtl} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.Meshpart1Mtl} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.Meshpart2Mtl} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.Meshpart2Mtl} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.Meshpart4Mtl} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.Panel11Mtl} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.Seat1Mtl} />
      </group>
    </group>
  )
}

useGLTF.preload('./cirrussr22.gltf')
